# Generated by Django 2.2.12 on 2020-04-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_app', '0003_auto_20200408_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agileprinciples',
            old_name='definitions',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='agilevalues',
            old_name='definitions',
            new_name='definition',
        ),
    ]
